# Travis CI integration -- https://travis-ci.org/troglobit/uredir
# Defaults to GNU GCC and autotools: ./configure && make && make test
language: c

# Use docker for quicker builds, it now allows https://docs.travis-ci.com/user/apt/
sudo: false

# Test build with both GCC and Clang (LLVM)
compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - tree

install:
  - wget https://github.com/troglobit/libuev/releases/download/v2.1.1/libuev-2.1.1.tar.xz
  - tar xf libuev-2.1.1.tar.xz
  - (cd libuev-2.1.1 && ./configure --prefix=/tmp && make && make install-strip)

# Custom build script for the time being, no "make test" yet
script:
  - ./autogen.sh
  - PKG_CONFIG_PATH=/tmp/lib/pkgconfig ./configure --prefix=/tmp
  - make clean
  - make V=1 -j5
  - make install-strip
  - PKG_CONFIG_PATH=/tmp/lib/pkgconfig make distcheck
  - tree /tmp/
  - ldd /tmp/bin/uredir
  - size /tmp/bin/uredir
  - LD_LIBRARY_PATH=/tmp/lib /tmp/bin/uredir -h
